### ISSUE TITLE
Aether 2 leaf compatibility

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Passable-Leaves#10]

**Comment by srs-bsns** [comment]
This is an Aether II issue. Their leaf blocks extend `net.minecraft.block.Block` and not `net.minecraft.block.BlockLeaves`. All of the magic happens in BlockLeaves, so if their leaf blocks don't extend this class then they will never be passable with PassableLeaves.

Reference: https://git.gildedgames.com/GildedGames/Aether-II/blob/dev/src/main/java/com/gildedgames/aether/common/blocks/natural/BlockAetherLeaves.java

CC: @JellySquid3 @kingbdogz

**Comment by jellysquid3** [comment]
I've opened an issue on our issue tracker [here](https://git.gildedgames.com/GildedGames/Aether-II/issues/660) regarding it.

**Comment by whichonespink44** [comment]
This has been closed on the Aether II tracker, so closing here.
