### ISSUE TITLE
Update for 1.12.1

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Passable-Leaves#11]
could you update to forge 2469 please? latest version does not work on that version. game runs but i cant pass leaves.
thank you

**Comment by Shadows-of-Fire** [comment]
The coremod won't run on that version due to it being declared as 1.12 only and not 1.12.1
The update will literally be the addtion of two characters to the version string as soon as someone with upload access to the curse page decides to do it.

**Comment by Tokeli** [comment]
Is it possible for someone to upload a compiled version elsewhere in the meantime? I've been trying to do it myself with no success, as I have no clue what I'm doing.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.util.zip.ZipException: duplicate entry: net/minecraft/command/AdvancementCommand$Mode.class
```

**Comment by whichonespink44** [comment]
Updated to 1.12.1 - release can be downloaded here until it gets pushed to Curse:

https://github.com/Team-RTG/Passable-Leaves/releases/tag/v1.12.1-6.2.0.0
