### ISSUE TITLE
Update for 1.12.2

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Passable-Leaves#13]
hi again, please update to 1.12.2 :D mod works with no crash but i cant pass leaves

**Comment by ghost** [comment]
anyone hear me? =(

**Comment by srs-bsns** [comment]
It's being worked on. It will be released when it's ready.

**Comment by ghost** [comment]
...

**Comment by srs-bsns** [comment]
@kenijey, sorry for the delay. @whichonespink44 handles the releases for this mod and he's been too preoccupied with IRL stuff lately. I'd release it myself, but I don't have access to the CurseForge project.

If you really want to use it now, you can get this zip: https://github.com/srs-bsns/Passable-Leaves/archive/1.12-dev.zip
Unpack the zip anywhere and from the root directory, run the console command: `gradlew build`
The jar will be in `./build/libs/`

**Comment by ghost** [comment]
Thannnnnk ypu very very much. Yeah i know how to build a jar by gradle. Thanks :)

**Comment by Tokeli** [comment]
It's been over half a year, and the code has an MIT license. Does someone want to just put up the 1.12.2 build on Curse with a link to the original? I've been using it for a while and can confirm it works perfectly.

**Comment by whichonespink44** [comment]
@Tokeli I've been out of the loop for a while, but I'll try to get this onto CurseForge tonight.

**Comment by srs-bsns** [comment]
This isn't ready for release yet. There are still things that need to be done.

**Comment by Ezoteric** [comment]
lel

**Comment by Tokeli** [comment]
I've been using it since October with no issues, so it seems to work enough to throw up on Curseforge in the meantime? Only problem I can see is the culling of block sides when using Fast graphics.

**Comment by whichonespink44** [comment]
Sorry for speaking so soon... @srs-bsns is right, it's not quite ready to be released yet. But it's on our radar, so hopefully we'll be moving closer to a release soon.

**Comment by srs-bsns** [comment]
1. The coremod part of this mod has to be fixed to meet recent changes to Forge coremod standards.
2. Proper testing needs to be done for use on dedicated servers.

It doesn't matter how long you've been using a custom made jar from the PR, it won't be released until it is ready. Besides, if you're already using it, I'm not sure why you even care if it's on CurseForge anyways.

Also, no one else has been asking about it, so it's low priorty at the moment.
