### ISSUE TITLE
Game do not start with last recomended Forge

### ISSUE THREAD

**Issue by Bulldog83** [Team-RTG/Passable-Leaves#20]
There is no crash report, but here is server log: https://gist.github.com/Bulldog83/5de3ece79333d11c3db9245e80057dfe

W/o Passable Leaves game starts.

Minecraft: 1.12.2
Forge: 14.23.5.2768
Passable Leaves: 2.0.0

**Comment by ThelianTech** [comment]
Please Refer to Issue #19
