### ISSUE TITLE
Mobs that doesn't take fall damage when fall on leaves with this mod, take fall damage

### ISSUE THREAD

**Issue by mser7** [Team-RTG/Passable-Leaves#23]
I was playing around with Ice and Fire mod, they have flying tamable mobs that is supposed to immune to fall damage, and I had a few of mine fly around, but when they landed, I notice they take a huge chunk of damage, this only happen ever since I install this mod.
![2019-01-03_10 08 07](https://user-images.githubusercontent.com/22555489/50734312-e9355600-11cf-11e9-981a-15ba82120ff9.png)

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Passable-Leaves/pull/24#issuecomment-504783489
