### ISSUE TITLE
[Suggestion] being able to add our own block 

### ISSUE THREAD

**Issue by Zack7292** [Team-RTG/Passable-Leaves#26]
Hey, i'll like to be able to add my own block of leaves that you can pass through, bcs since its not compatible with Biome You'll Go, i'll like to add his leaves.

**Comment by MoeBoy76** [comment]
Leaves are only passable if they follow correct programming practices, in this case BYG follows basically none as it is a MCreator mod, have the mod developer switch to Forge and extend Vanilla's leaf block class

**Comment by Zack7292** [comment]
ik, that's literally why i ask this ._.
