### ISSUE TITLE
Passable Leaves suddenly requesting PassableLeavesCore when previously functional.

### ISSUE THREAD

**Issue by UnlimatedStone9** [Team-RTG/Passable-Leaves#28]
No idea why, this happened to me and another user in two different modpack instances entirely. On first mod load.
![image](https://user-images.githubusercontent.com/40124890/77093425-d7218b00-6a02-11ea-8bf4-448101364070.png)

**Comment by UnlimatedStone9** [comment]
I kept the game in focus and it loaded fine.
However I suspect what it really is, is one of those flukes where a mod doesn't load the first time.
This happens to some mods for some reason. (from my own experience, and potentially others.)

**Comment by srs-bsns** [comment]
The only way something like that could happen _inconsistantly_ is through a race condition where some other coremod that modifies `BlockLeaves` is being initialized before _passableleavescore_, which would result in the core mod not being initialized at all.

In any sense, there isn't anything in PassableLeaves that would cause this. If the coremod doesn't get initialized, then the reason should be stated in the log files.
