### ISSUE TITLE
Snow on leaves isn't passable

### ISSUE THREAD

**Issue by spelenza** [Team-RTG/Passable-Leaves#29]
Unfortunately, **snow on top of leaves isn't passable**. This completely ruins the gameplay!

Snow layers should be passable too, with configurable speed (like leaves)
Same for lily pads.

**Comment by srs-bsns** [comment]
Duplicate of #18

**Comment by ghost** [comment]
Any resolution for this??

**Comment by srs-bsns** [comment]
It was clearly stated more than 3 years ago in the other closed issue, that you also necroposted in back in Sept., why this is never going to happen.
This mod has been out of development for more than 2 1/2 years now. No sane person is still working on mods for 1.12.
