### ISSUE TITLE
Remove ASM stuff into its own mod

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Passable-Leaves#6]
As per http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/

**Comment by srs-bsns** [comment]
Considering that the policy change is a guideline and not a rule, and the fact that the PassableLeaves mod is really only a way to configure the coremod, there isn't really any need to separate the two any further.

If things change in the future, then we can change it then, but for now we can just keep it the way it is.
