### ISSUE TITLE
Can't jump out of leaves

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Passable-Leaves#7]
PassableLeaves-1.12-6.1.0.0

When you have a leaf block and a grass block next to each other, and you stand inside the leaf block, you can't jump the 1 block up that you need to get onto the dirt block.  This means that a pile of leaf blocks on the ground or in a hole becomes like quicksand.

**Comment by Konlii** [comment]
Any leaf blocks immediately above your head also stop you from jumping.  It would be nice if holding space allowed you to climb up through leaf blocks.

**Comment by whichonespink44** [comment]
This isn't something I think we need to change. After all, if you were standing in a pile of leaves, it would impair your ability to jump. Also, you can always just break the leaves if you ever get stuck.

**Comment by Konlii** [comment]
You've never climbed a tree IRL?  It usually **requires** some branches, i.e. leaf blocks, to grab hold of.

**Comment by superckl** [comment]
You're right that a pile of leaves would impair your jump, but it certainly wouldn't act like a ceiling. This is definitely a bug that should be fixed in my opinion.

**Comment by lightningo7** [comment]
I believe it will still allow you to jump, just not all the way up a block. As for the climbing stuff, it really isn't within the scope of this mod. On another note to climb trees, you grab the branches, not the leaves so that would require either logs or branches.

**Comment by whichonespink44** [comment]
Yeah, leaves aren't branches... leaves are leaves... and you can't climb out of a pile of leaves.

However, I can see how some folks would find it annoying or counter-intuitive, so... I guess it wouldn't hurt to have it as a config option.

If that's the route we go down though... how exactly would we implement it? We already have the `"Rate of speed when passing through leaves along the {X|Y|Z} axis."` options... would this be something different?

Maybe something like `Make leaves climbable={true|false}` ? Would also need to make the key binding configurable, and everything that goes along with that.

**Comment by Konlii** [comment]
Could you guys simply make rate of speed when passing through leaves along the positive Y a separate config option from the rate of speed when passing through leaves along the negative Y?  If those are the same number, you will have the same behavior as the current implementation.
