### ISSUE TITLE
1.12 Xray vision

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Passable-Leaves#9]
PassableLeaves-1.12-6.1.0.0
Having your head in a leaf block - for example if there's a 2-high pile of leaf blocks and you're standing in it - gives you xray vision allowing you to look through the world.

**Comment by whichonespink44** [comment]
This has been confirmed in 1.10.2, 1.11.2 and 1.12.

Only happens with 'Fast' graphics... 'Fancy' graphics works as expected.

**Comment by Shadows-of-Fire** [comment]
Its because being inside a fully opaque block culls those faces, so you either have to lock leaves to fancy, or disable their culling.

**Comment by whichonespink44** [comment]
Makes sense... so to disable culling, I guess we'd need to add this to the ASM we're doing?
```
    public boolean isOpaqueCube(IBlockState state) {
        return false;
    }
```

**Comment by Shadows-of-Fire** [comment]
@HellFirePvP

**Comment by HellFirePvP** [comment]
On it tomorrow.

**Comment by srs-bsns** [comment]
This can likely be done in the future, but considering the unpopularity of running the game with fast graphics by most users this is low-priority.

**Comment by PixelmonPRO** [comment]
@srs-bsns any news about fix it?)

**Comment by srs-bsns** [comment]
1.12 is EOL, and so is this mod.
